### ISSUE TITLE
Failed to activate the git-travel package

### ISSUE THREAD

**Issue by varemenos** [varemenos/atom-git-travel#1]
1. Install git-travel
2. Open Atom

**Atom Version**: 1.3.2
**System**: "Arch Linux"
**Thrown From**: [git-travel](https://github.com/varemenos/atom-git-travel) package, v0.1.0

### Stack Trace

Failed to activate the git-travel package

```
At Cannot find module '../build/Debug/nodegit.node'

Error: Cannot find module '../build/Debug/nodegit.node'
  at Module._resolveFilename (module.js:336:15)
  at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:286:25)
  at Module.require (module.js:365:17)
  at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/home/adonisk/.atom/packages/git-travel/node_modules/nodegit/lib/nodegit.js:16:12)
  at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/home/adonisk/.atom/packages/git-travel/lib/main.js:3:15)
  at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:663:34)
  at Package.module.exports.Package.activateConfig (/usr/share/atom/resources/app.asar/src/package.js:188:14)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:166:14)
  at /usr/share/atom/resources/app.asar/src/package.js:740:25
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:20)
  at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:160:19)
  at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/usr/share/atom/resources/app.asar/src/atom-environment.js:1016:28)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:172:7)
  at EventEmitter.ipc.sendSync (/usr/share/atom/resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/usr/share/atom/resources/atom.asar/renderer/api/lib/remote.js:143:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/usr/share/atom/resources/app.asar/src/context-menu-manager.js:156:33)
  at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (/usr/share/atom/resources/app.asar/src/window-event-handler.js:250:47)
  at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)

```

### Commands

```
     -0:02.9.0 git-travel:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "wrap-guide",
      "language-javascript-jsx"
    ],
    "packagesWithKeymapsDisabled": [
      "tree-view-git-status",
      "git-diff",
      "browser-plus",
      "expand-region",
      "linter"
    ],
    "projectHome": "~/repos",
    "themes": [
      "one-dark-ui",
      "duotone-denim-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
auto-detect-indentation, v0.4.2
autoclose-html, v0.19.0
browser-plus, v0.0.54
docblockr, v0.7.3
duotone-denim-syntax, v0.3.3
editorconfig, v1.2.2
emmet, v2.3.17
exception-reporting, v0.37.0
file-icons, v1.6.13
file-types, v0.5.1
git-travel, v0.1.0
gtk-dark-theme, v0.1.4
hidpi, v0.11.0
highlight-selected, v0.11.1
language-apache, v1.4.0
language-dircolors, v1.2.0
language-graphql, v0.2.0
language-ini, v1.14.0
language-jade, v0.6.2
language-liquid, v0.4.0
language-log, v1.1.0
line-diff-details, v1.1.3
line-ending-selector, v0.3.0
linter, v1.11.3
linter-eslint, v5.2.7
linter-jscs, v3.2.1
linter-jshint, v1.2.2
linter-jsonlint, v1.1.3
linter-jsxhint, v0.1.2
minimap, v4.19.0
minimap-find-and-replace, v4.4.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-linter, v1.1.0
nuclide-flow, v0.0.35
project-manager, v2.6.5
set-syntax, v0.3.0
sync-settings, v0.6.0
tabulation-control, v1.0.7
tool-bar, v0.1.9
tool-bar-almighty, v0.5.0
tree-view-git-status, v0.2.2

# Dev
No dev packages
```

**Comment by varemenos** [comment]
seems to be related to https://github.com/nodegit/nodegit/issues/137
possible fix: http://www.nodegit.org/guides/install/from-source/

**Comment by varemenos** [comment]
The only way I've managed to fix this was by doing the following:

```shell
cd ~/.atom/packages/git-travel/node_modules/nodegit #assuming ~/.atom is your atom's configuration location
npm run installDebug #using Node v4.2
```

**Comment by hendrikstier** [comment]
I tried the suggested fix (using install and installDebug as options), resulting in the following error message, when toggling git travel:

```javascript
Module version mismatch. Expected 46, got 47.
```

**Comment by varemenos** [comment]
What version of node were you using when you executed `npm run installDebug` I'm really not sure which module version it's referring to, could be nodegit could be one of its dependencies?

**Comment by hendrikstier** [comment]
Versions are:

```shell
> node -v                                                                                            ruby-2.3.0-preview2@rsl-middleman
v5.3.0
> npm -v                                                                                             ruby-2.3.0-preview2@rsl-middleman
3.3.12
```

Which package.json should I best modify to test? Would it make sense to grep for "46" in all of the package-manifests?

**Comment by varemenos** [comment]
Not really sure, probably mess with the Node and Nodegit versions (if you are using a node version manager, switch to v4.2 and try `npm run installDebug` again).
Sorry for late and non useful replies but I'm currently sick :mask: so I'm periodically checking my phone and reply from there.

**Comment by hendrikstier** [comment]
Now using

```shell
> node -v && npm -v                                                                                       ruby-2.3.0-preview2@rsl-middleman
v4.2.4
2.14.12
```

I built it again, now the error message reads:

**Atom Version**: 1.4.0-beta3
**System**: Mac OS X 10.11.2
**Thrown From**: [git-travel](https://github.com/varemenos/atom-git-travel) package, v0.1.3


### Stack Trace

Uncaught ReferenceError: path is not defined

```
At /Users/hs/.atom/packages/git-travel/lib/utils.js:7

ReferenceError: path is not defined
    at Object.getRepo (/Users/hs/.atom/packages/git-travel/lib/utils.js:7:18)
    at Object.GitTravel.getReferences.utils.getRepo.then.Promise.all.then.GitTravel.getCommits.utils.getRepo.then.then.then.history.on [as getCommits] (/Users/hs/.atom/packages/git-travel/lib/main.js:42:9)
    at Object.GitTravel.getReferences.utils.getRepo.then.Promise.all.then.GitTravel.getCommits.utils.getRepo.then.then.then.GitTravel.toggle (/Users/hs/.atom/packages/git-travel/lib/main.js:99:10)
    at atom-workspace.subscriptions.add.atom.commands.add.git-travel:toggle (/Users/hs/.atom/packages/git-travel/lib/main.js:78:39)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:03.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:01.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.5.0 git-travel:toggle (atom-text-editor.editor)
```

**Comment by varemenos** [comment]
ok so that's a stupid thing from my part, it seems I have path as a locally installed dependency but for some reason removed it. It should work once I send a patch to fix this issue. Afterwards I need to investigate why it only works with v4.2.

**Comment by laughedelic** [comment]
Still encounter this bug

**Comment by brycefranzen** [comment]
Still having this error

**Comment by gnarmedia** [comment]
Still an issue :/
