### ISSUE TITLE
Uncaught Error: Cannot find module '../build/Debug/nodegit.node'

### ISSUE THREAD

**Issue by marnen** [varemenos/atom-git-travel#2]
This error was thrown during installation of the package.

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [git-travel](https://github.com/varemenos/atom-git-travel) package, v0.1.4

### Stack Trace

Uncaught Error: Cannot find module '../build/Debug/nodegit.node'

```
At module.js:338

Error: Cannot find module '../build/Debug/nodegit.node'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/mlaibowkoser/.atom/packages/git-travel/node_modules/nodegit/lib/nodegit.js:16:12)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/mlaibowkoser/.atom/packages/git-travel/lib/main.js:3:15)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:663:34)
    at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:188:14)
    at PackageDetailView.module.exports.PackageDetailView.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:216:26)
    at PackageDetailView.module.exports.PackageDetailView.completeInitialzation (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:159:12)
    at PackageDetailView.module.exports.PackageDetailView.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:171:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:302:17
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:664:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:452:26
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -4:25.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:25.4.0 stacktrace:to-caller (atom-text-editor.editor)
     -4:16.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:15.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:43 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:05.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -2:58.6.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -2:58.6.0 git-diff-details:close-git-diff-details (atom-text-editor.editor.mini.is-focused)
     -2:58.6.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -2:55.5.0 git-diff:toggle-diff-list (atom-text-editor.editor.is-focused)
     -2:54.2.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -2:54.2.0 git-diff-details:close-git-diff-details (atom-text-editor.editor.mini.is-focused)
     -2:54.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -2:53.5.0 core:close (atom-text-editor.editor.is-focused)
  5x -2:34.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:32.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
coffee-compile, v0.21.0
cucumber, v0.5.0
file-type-icons, v0.7.4
git-diff-details, v0.21.0
git-log, v0.4.1
imdone-atom, v1.3.16
language-haml, v0.23.14
monokai, v0.18.0
pigments, v0.19.5
regex-railroad-diagram, v0.10.4
revert-buffer, v0.5.0
ruby-block, v0.3.5
stacktrace, v0.0.2
tree-view-git-status, v0.2.2

# Dev
No dev packages
```

**Comment by varemenos** [comment]
Please see #1
